### ISSUE TITLE
errors on activate theme... how to resolve 

### ISSUE THREAD

**Issue by akwatra** [salcode/bootstrap-genesis#106]
Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method Genesis_Tabs::init() should not be called statically in /www/htdocs/genesis/wp-includes/plugin.php on line 503

Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method Genesis_Tabs::register_widget() should not be called statically in /www/htdocs/genesis/wp-includes/plugin.php on line 503

Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method Genesis_Tabs::register_scripts() should not be called statically in /www/htdocs/genesis/wp-includes/plugin.php on line 503

Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method Genesis_Tabs::register_styles() should not be called statically in /www/htdocs/genesis/wp-includes/plugin.php on line 503

Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method Genesis_Tabs::footer_js() should not be called statically in /www/htdocs/genesis/wp-includes/plugin.php on line 503

**Comment by salcode** [comment]
Hi @akwatra,

I do my development with

```
define('WP_DEBUG', true);
```

defined in `wp-config.php` and I've not seen these warnings before.

I also notice that all of the paths listed reference **genesis**, not **bootstrap-genesis**, which makes me wonder if these are related to the Genesis parent theme rather than the child theme.

Would you please:
1.  Try and activate the Genesis parent theme and see if the problem occurs there
2.  Provide further information on you have your site configured, so I can recreate your setup

Thanks.

**Comment by bryanwillis** [comment]
As far as I'm aware this isn't an issue with Bootstrap Genesis.

You're using Genesis Tabs or Genesis Tabs Extended plugin I'm assuming? 

https://wordpress.org/support/topic/php-strict-standards-wp_widget-deprecated?replies=1

https://wordpress.org/support/topic/still-supported-multiple-php-strict-php-notices?replies=1

**Comment by bryanwillis** [comment]
You can try installing the [genesis starter child theme](https://docs.google.com/uc?authuser=0&id=0B5AIGpmXiSKVNTVPTEExdl9DMEk&export=download). If you still get the issue with that then we know without question that it has nothing to do with Bootstrap Genesis.

If you are using Genesis Tabs and still getting the issue with the Starter Child Theme it's good this is being addressed since that plugin is actually maintained by the Genesis theme developers (Note that Genesis Tabs only works with a child theme... which may or may not have to do with the issue).

Also, this might just have to do with your version of Genesis and or one of the plugins. Are you using the latest version of everything?

**Comment by salcode** [comment]
@akwatra since we haven't heard anything further about this, I'm going to close this issue.  If you still suspect the problem lies with Bootstrap Genesis and you want to provide more information, we can re-open this issue.

**Comment by akwatra** [comment]
Hi @salcode yes when i disabled few genesis plugin then errors were gone. 
but seems now i have to update those plugins.
