### ISSUE TITLE
Question: Justify the site title / logo to the inner content wrap?

### ISSUE THREAD

**Issue by christopherarter** [salcode/bootstrap-genesis#111]
Pardon my newbie question, I'm still just getting started with SASS, but how can I justify the logo / title area (along with the menu) to the inner content wrap like this: http://getbootstrap.com/examples/theme/

As I'm seeing it on a fresh install, it's float-left all the way. Just curious what variable I would change. Also, how would I float the menu right and the title/logo left?

Thanks!

**Comment by salcode** [comment]
It looks like http://getbootstrap.com/examples/theme/ has the nav wrapped in 

```
<div class="container">
```

while we're using 

```
<div class="container-fluid">
```

You can change this in `lib/nav.php`.

I'm not sure why we chose `container-fluid` over `container` for this class but it looks like always did it that way since the beginning (commit c5fb57860d8 is where this originally shows up)
